file = open("student.txt", "r")
content = file.read()
file.close()
modified_content = content.replace("Siddhi", "Hello")
file = open("student.txt", "w")
file.write(modified_content)
print(modified_content)
file.close()
print("Word replaced successfully.")